### ISSUE TITLE
Add put and delete api methods

### ISSUE THREAD

**Issue by OscarSalgado** [matin/garth#11]
They are useful to interact with other services, i.e. workout-service among others

**Comment by matin** [comment]
Happy to add them.

What endpoint uses PUT? I need it to be able to write a test.

For DELETE, I can add use weigh ins.

**Comment by OscarSalgado** [comment]
For example you can use this endpoint https://github.com/OscarSalgado/garmin-workouts/blob/bec64cff1c7de2bcaefa7ec739b516cc71a3a736/garminworkouts/garmin/garminclient.py#L408
used to update your HR zones. Get first the adequate payload.

There are other endpoints using PUT, but you will need first a existing workout, or event for example.

**Comment by matin** [comment]
I'll add DELETE and look into PUT this weekend. In the meantime, you can always use `Client.request()` directly like this:

```python
garth.client.request(
    "DELETE",
    "connectapi",
    path,
    api=True,
)
```
