### ISSUE TITLE
Give a hint in the documentation, howto install garth

### ISSUE THREAD

**Issue by telemaxx** [matin/garth#16]
On Debian Bookworm i could not install garth as described in the docu.

on [Stackoverflow](https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3) i found a solution.

Maybe we should give a hint in the documentation.

this steps solved it for me:

```
sudo apt install python3-pip
sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.OFF
python3 -m pip install garth

```

**Comment by matin** [comment]
I'm happy you found the solution!

This is very specific to Ubuntu / Debian. The README / docs should be more general to all platforms.

**Comment by helmut72** [comment]
> This is very specific to Ubuntu / Debian. The README / docs should be more general to all platforms.

Not really. Same is needed for Alpine Linux too when using Alpine that came with Python 3.11 and higher.
