### ISSUE TITLE
Sleep example in documentation.... spelling error

### ISSUE THREAD

**Issue by TerryGamon** [matin/garth#18]
Sleep example in documentation....
spelling error

sleep = garth.connectapi(
    f"/wellness-service/wellness/dailySleepData/{garth.client.username}",
    params={"date": "2023-07-05", "nonSleepBufferMinutes": 60),
)

maybe?

sleep = garth.connectapi(
    f"/wellness-service/wellness/dailySleepData/{garth.client.username}",
    params={"date": "2023-07-05", "nonSleepBufferMinutes": 60}
)

**Comment by matin** [comment]
@TerryGamon thanks for reporting the issue! Fixed.
