### ISSUE TITLE
"Update Phone Number" when signin

### ISSUE THREAD

**Issue by gooin** [matin/garth#19]
Thank you, @matin for your work on the this lib. I used your code as a basis for refactoring the `garmin-connect` which is a typescript lib for garmin connect [https://github.com/Pythe1337N/garmin-connect/pull/56](https://github.com/Pythe1337N/garmin-connect/pull/56)

When the account has a phone number, the library works fine. However, if the account doesn't have a phone number, the POST request during the sign-in step returns an HTML page with the title "Update Phone Number", which causes the login to fail. If everything goes well, the title should be "Success".

Does anyone know how to add a phone number to a Garmin account? I tried adding a phone number on the MFA page, but I still can't see the phone number on the [https://www.garmin.com/en-US/account/profile/](https://www.garmin.com/en-US/account/profile/) page.

[https://www.garmin.com/en-US/account/profile/](https://www.garmin.com/en-US/account/profile/)
## Have phone numbers account: 
![image](https://github.com/matin/garth/assets/13775365/4bec07e5-ddee-4ca6-87f2-a6c3051de497)
## Doesn't have phone numbers account: 
![image](https://github.com/matin/garth/assets/13775365/c77be8d5-93b1-4c45-87da-d8c87e8db166)

**Comment by gooin** [comment]
In https://github.com/Pythe1337N/garmin-connect/pull/56/commits/e82aa730357a08b23640991843fcbe7e825eb16f

**Comment by matin** [comment]
I see you're based in China, but it looks like you're using the Garmin US website. Have you tried using garmin.com.cn to enter the account?

Garmin is fairly specific about requiring requests from China to go through `.cn` domains. This was a fairly annoying part of the development, but a large number of the people using Garth are based in China.

I have some other ideas on what you could do, but I'd start there if, in fact, you're attempting access the account from China.

**Comment by matin** [comment]
On a separate note, it's amazing to see people like you migrating the Garth logic to other languages!

**Comment by gooin** [comment]
> I see you're based in China, but it looks like you're using the Garmin US website. Have you tried using garmin.com.cn to enter the account?
> 
> Garmin is fairly specific about requiring requests from China to go through `.cn` domains. This was a fairly annoying part of the development, but a large number of the people using Garth are based in China.
> 
> I have some other ideas on what you could do, but I'd start there if, in fact, you're attempting access the account from China.

Yes, I'm in China. There are many users in China who want to use Strava, but Strava cannot connect to Garmin.cn. So we tried to register an account on Garmin.com to connect to Strava, and then transfer the .fit files from Garmin.cn to Garmin.com. This way, we can use Strava. 

Today, I tried to reproduce this issue by registering a new account on connect.garmin.com. When I tried to log in using Garth's method, I also got the "Update Phone Number" prompt. I then tried logging in to the account using the Connect App, and after entering my password and clicking "Log In", the "Update Phone Number" page appeared. I entered my phone number and verified it, and then logged in using Garth's method, and everything worked fine.

 I hope this helps anyone who encounters the same issue.

**Comment by matin** [comment]
Try https://www.garmin.cn/account instead of the Connect app or website, and let me know if that works

**Comment by Dunky-Z** [comment]
@matin Thanks for your reply. I encountered the same issue as gooin, and it can now be resolved by following the steps I described earlier (disabling the VPN, logging into the Connect app, and updating the phone number). I'm replying to this issue to provide a reference for others who might face the same problem in the future.
