### ISSUE TITLE
garth.SleepData: DailySleepDTO missing 'sleep_from_device' and 'sleep_version' 

### ISSUE THREAD

**Issue by andgineer** [matin/garth#22]
When I do in provided colab notebook
garth.SleepData.get("2023-10-03")

I get error:
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
[<ipython-input-15-a0607f0b023c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 garth.SleepData.get("2023-10-03")

2 frames
/usr/local/lib/python3.10/dist-packages/pydantic/dataclasses.cpython-310-x86_64-linux-gnu.so in pydantic.dataclasses._dataclass_validate_values()

ValidationError: 1 validation error for SleepData
daily_sleep_dto
  DailySleepDTO.__init__() missing 2 required positional arguments: 'sleep_from_device' and 'sleep_version' (type=type_error)

**Comment by matin** [comment]
What happens when you call the endpoint directly?

```python
garth.connectapi(f"/wellness-service/wellness/dailySleepData/{garth.client.username}?nonSleepBufferMinutes=60&date=2023-10-03")
```

**Comment by andgineer** [comment]
it works if I use that
and garth.SleepData.get("2023-10-03") return the same error

**Comment by matin** [comment]
Working on a fix #23

**Comment by matin** [comment]
@andgineer can you try version `0.4.37`?

**Comment by andgineer** [comment]
hm in the colab
Successfully installed garth-0.4.37

but the error the same (I repeated all steps in the notebook)

may be I should refresh something?

**Comment by matin** [comment]
If you're in Colab, you have to disconnect and delete runtime. When you restart, it'll install the latest version.

You can check `garth.__version__` to verify.

**Comment by andgineer** [comment]
%pip install garth --upgrade
Requirement already satisfied: garth in /usr/local/lib/python3.10/dist-packages (0.4.37)

import garth
garth.__version__ 
0.4.36

**Comment by matin** [comment]
Did you disconnect and delete the runtime?

Colab can't upgrade a package in the same environment. It won't load the new version.

**Comment by andgineer** [comment]
sorry for all the confusion
in .37 it works

thank you for blazingly fast fix

**Comment by matin** [comment]
@andgineer out of curiosity, did you find the graphs generated by the Colabs useful / interesting?

**Comment by andgineer** [comment]
honestly, I could not see any dependencies
even I know they exist just because I changed my habits significantly

but you know that could be the question of Garmin data that they just do not reflect the changes
