### ISSUE TITLE
readme issue

### ISSUE THREAD

**Issue by tcgoetz** [matin/garth#26]
In the https://github.com/matin/garth#attempt-to-resume-session section of the readme, this line seems to be incorrect. The client part is not needed:

` garth.client.username`

**Comment by tcgoetz** [comment]
Also, the save and resume section refers to save and resume, but the code has load and dump.

**Comment by matin** [comment]
In the README, `garth` refers to the module, and `garth.client` is a global instance of `garth.http.Client` that's used in scripts for convenience.

In GarminDB, `Download.garth` is an instance of `garth.http.Client`.

Sorry for any confusion in the naming convention.
