### ISSUE TITLE
pydantic 1.10.12

### ISSUE THREAD

**Issue by encodedLife** [matin/garth#32]
First of all I wanted to express my appreciation for your work – your library is fantastic and has been incredibly useful.
 
I'm currently developing a custom integration for HomeAssistant, which relies on pydantic version 1.10.12 as part of its core dependencies. Would it be feasible for you to adjust the minimum required version of your library to be compatible with pydantic 1.10.12?

**Comment by matin** [comment]
Thank you for the kind words! I'm happy that you've found is so useful.

It's certainly feasible. I'll make the change now.

**Comment by matin** [comment]
@encodedLife [v0.4.40](https://github.com/matin/garth/releases/tag/0.4.40) now supports Pydantic 1.10.12. Thanks for reporting the issue.

**Comment by encodedLife** [comment]
Thank you for the prompt reply and quick implementation.
