### ISSUE TITLE
No matching distribution found for garth

### ISSUE THREAD

**Issue by pavlinux** [matin/garth#34]
```
# python -m pip install garth
Collecting garth
  Could not find a version that satisfies the requirement garth (from versions: )
No matching distribution found for garth

```

**Comment by matin** [comment]
what version of python are you running?

**Comment by pavlinux** [comment]
> what version of python are you running?

Python 3.7.3
or 
Python 2.7.16

**Comment by matin** [comment]
Garth has a min version requirement of 3.8. Are you able to upgrade?

**Comment by pavlinux** [comment]
> Garth has a min version requirement of 3.8. Are you able to upgrade?

I can, but I won't. Not critical. ;)

**Comment by matin** [comment]
Fair enough. In the meantime, you should check out Google Colab or similar hosted Notebooks if you want to experiment with Garth

**Comment by pavlinux** [comment]
> Fair enough. In the meantime, you should check out Google Colab or similar hosted Notebooks if you want to experiment with Garth

Garth used in https://github.com/pe-st/garmin-connect-export

**Comment by matin** [comment]
Looks like the [README for garmin-connect-export ](https://github.com/pe-st/garmin-connect-export#garmin-connect-export-script) calls for Python 3.8 as the min version
