### ISSUE TITLE
Async client?

### ISSUE THREAD

**Issue by Fingel** [matin/garth#53]
Hi,
Nice work on this! I was considering using Garth for an interactive application. It would require making the http requests asynchronous. There are of course ways to achieve this at a higher level. But since this project is relatively small, and we have [httpx](https://www.python-httpx.org/) now, I'd figured I'd get your thoughts on asyncio.
I'd of course be willing to contribute this. Browsing the code, it looks like it could be possible to abstract some stuff out of http.Client and provide 2 clients, one that is sync and one that is async. sso.py would be a little annoying to duplicate, I might have to look into how other libraries handle providing both. 
Of course this is assuming you are interested in an async interface at all. I figure it's better than an entire different project or fork. What do you think?

**Comment by matin** [comment]
@Fingel have you tried asyncer?
