### ISSUE TITLE
Not working for China domain

### ISSUE THREAD

**Issue by mmlbing** [matin/garth#55]
Hi nice day!
Looks the lib not working for China domain anymore..
I have tested with 2 CN accounts, even tried reset the password.
All no luck  TT

**Comment by matin** [comment]
@yihong0618 have you run into the same issue?

@mmlbing can you write a test that shows the failure along with the recorded VCR cassette?

**Comment by yihong0618** [comment]
will test today

**Comment by yihong0618** [comment]
@matin my side work well

**Comment by matin** [comment]
@yihong0618 I appreciate you checking!

@mmlbing what error are you receiving?

**Comment by matin** [comment]
I can't reproduce, and the author of the issue hasn't responded.

**Comment by mmlbing** [comment]
Sorry for late reply. Just made a test and everything works great, maybe my problem was caused by some network\account issues (I was doing many logon\logoff tests..).
Many thanks again! This project is great! :D
