### ISSUE TITLE
Record VCR cassette of login from China

### ISSUE THREAD

**Issue by matin** [matin/garth#6]
@yihong0618 I have a favor to ask ... Can you add a test (along with the VCR cassette) for login from China?

I spent a bunch of time to make sure it can work from China by allowing for a custom domain, but it hasn't been tested.

Using `garth.configure(domain="garmin.cn")` before the login _should_ be sufficient 🤞

Let me know if you run into any issues (along with the error) for me to fix it. I want to make sure everyone is able to use Garth.

**Comment by yihong0618** [comment]
@matin it works well for `garth.configure(domain="garmin.cn")` you can check
will try to add test, thanks https://github.com/yihong0618/running_page/blob/master/run_page/get_garmin_secret.py
and my code changed commit https://github.com/yihong0618/running_page/commit/6c9d49b5e048fd257d85ab0a39a841e99da2c25c

**Comment by matin** [comment]
Great to hear! Happy to know the time was well spent!

**Comment by matin** [comment]
Closing this—as there are now multiple people using https://github.com/yihong0618/running_page with the Garth integration from China. That gives me the confidence that it works properly.
