### ISSUE TITLE
Upload data to Garmin Connect account in China

### ISSUE THREAD

**Issue by joe-zhang3** [matin/garth#67]
Hi, 

As you may aware that there some difference for Garmin account in China region vs other regions. I have two accounts, well I originally only have one which is the international one, where I can share my activities to Strava etc. But it does have some drawbacks as the connection is very slow (probably because the server is sitting out of China, so it takes a while to syncup ). 

Hence I register a new Garmin connect account for China only, and it works faster than the original one. But I will not be able to link my China specific Garmin account with Strava. 

So the idea is using my China Garmin account and syncup data to the global one where I can sync up to Strava accordingly. ( I did find out a way of using fit upload file to achieve this)

However it is not working for health data (sleep, hrv etc). I like this git repo and appreciate your help with putting everything together, but is there any way that I can upload data (activities, health data ) to Garmin server? or do you happen to have a full list of available APIs/endpoints etc so that I can have a try by myself?

**Comment by matin** [comment]
Did you try this?

https://github.com/matin/garth?tab=readme-ov-file#set-domain-for-china

**Comment by kvnZero** [comment]
我最近也有同样的需求并且使用garth已经开发完毕，可以参考一下
I also have the same requirement recently and use garth completed develop, you can  refer it
[GarminSync](https://github.com/kvnZero/IGPSPORT2Xingzhe/blob/main/GarminSync.py)

**Comment by matin** [comment]
@joe-zhang3 I'm closing this issue. looks like it's working for others like @kvnZero 

let me know if I can help in any other way
