### ISSUE TITLE
Support Fit File Upload

### ISSUE THREAD

**Issue by jrast** [matin/garth#8]
In https://github.com/jaroslawhartman/withings-sync/pull/132 I implemented the upload of `*.fit` files. Any interest to move this code to garth?

**Comment by matin** [comment]
Let me take a look. I'm sure it'd also be useful to others.

**Comment by matin** [comment]
@jrast could you give #9 a try?

I wanted to find a to make it generalized.

You can do the following:

```python
with open(fpath) as f:
    garth.client.upload(f)
```

**Comment by jrast** [comment]
Of course, If #9 is working go ahead and close this PR in favor of #9.
I will check if #9 is working but I will need some days (probably next week).
